/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;


/**
 *
 * @author jessl
 */
public class DisplayMenu extends javax.swing.JPanel {

    /**
     * Creates new form DisplayMenu
     */
    public DisplayMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _Display = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        _Display.setBackground(new java.awt.Color(238, 230, 220));
        _Display.setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Americano2.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 100, 100);

        _Display.add(jPanel1);
        jPanel1.setBounds(10, 10, 100, 100);

        jPanel2.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Carajillo2.jpg"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 100, 100);

        _Display.add(jPanel2);
        jPanel2.setBounds(10, 230, 100, 100);

        jPanel3.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Frape2.jpg"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 0, 100, 100);

        _Display.add(jPanel3);
        jPanel3.setBounds(10, 340, 100, 100);

        jPanel4.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Capuccino2.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3);
        jLabel3.setBounds(0, 0, 100, 100);

        _Display.add(jPanel4);
        jPanel4.setBounds(10, 120, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ic_volume_up_24px.png"))); // NOI18N
        _Display.add(jLabel1);
        jLabel1.setBounds(410, 410, 40, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 16)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Favor de hacer click\nen alguna de las \nImagenes para obtener \nuna descripcion del café");
        jScrollPane1.setViewportView(jTextArea1);

        _Display.add(jScrollPane1);
        jScrollPane1.setBounds(140, 10, 260, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_Display, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_Display, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            // TODO add your handling code here:
            Sound(1);
            _Display.setBackground(PastelYel);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DisplayMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            // TODO add your handling code here:
            Sound(4);
            _Display.setBackground(PastelOrg);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DisplayMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            // TODO add your handling code here:
            Sound(3);
            _Display.setBackground(PastelRed);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DisplayMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        try {
            // TODO add your handling code here:
            Sound(2);
            _Display.setBackground(PastelGrn);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DisplayMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    public void Sound(int a) throws FileNotFoundException{
        
        String SFX = "";
        
        switch(a){
            
            case 1:
                SFX = "D.wav";
            break;
            
            case 2:
                SFX = "A.wav";
            break;
            
            case 3:
                SFX = "C.wav";
            break;
            
            case 4:
                SFX = "G.wav";
            break;
            
            default:
                SFX = "N.wav";
            break;
        }
        
        try {
    File yourFile = new File(SFX);
    AudioInputStream stream;
    AudioFormat format;
    DataLine.Info info;
    Clip clip;

    stream = AudioSystem.getAudioInputStream(yourFile);
    format = stream.getFormat();
    info = new DataLine.Info(Clip.class, format);
    clip = (Clip) AudioSystem.getLine(info);
    clip.open(stream);
    clip.start();
    }
        catch ( IOException | LineUnavailableException | UnsupportedAudioFileException e) {
            //whatevers
    }
        
    }
    
    
    Color PastelRed = new Color(255, 179, 186);
    Color PastelOrg = new Color(255, 223, 186);
    Color PastelYel = new Color(255, 255, 186);
    Color PastelGrn = new Color(186, 255, 201);
    Color PastelBlu = new Color(186, 225, 255);
    Color Base = new Color(238,230,220);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _Display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
