/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author jessl
 */
public class DisplayOrden extends javax.swing.JPanel {

    /**
     * Creates new form DisplayMesas
     * @param a Establece la mesa actual
     */
    public DisplayOrden(int a) {
        initComponents();
        MesaActual = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _Display = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HoraDeUso = new javax.swing.JLabel();
        POrden = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PCuenta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        _Display.setBackground(new java.awt.Color(238, 230, 220));
        _Display.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Mesera.png"))); // NOI18N
        _Display.add(jLabel1);
        jLabel1.setBounds(10, 0, 150, 450);

        HoraDeUso.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        HoraDeUso.setForeground(new java.awt.Color(0, 0, 0));
        HoraDeUso.setText(" ");
        _Display.add(HoraDeUso);
        HoraDeUso.setBounds(160, 360, 270, 23);

        POrden.setBackground(new java.awt.Color(238, 230, 220));
        POrden.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 29, 27));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Pokedex.png"))); // NOI18N
        jLabel3.setText("  Orden");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        POrden.add(jLabel3);
        jLabel3.setBounds(10, 0, 230, 90);

        _Display.add(POrden);
        POrden.setBounds(190, 90, 240, 90);

        PCuenta.setBackground(new java.awt.Color(238, 230, 220));
        PCuenta.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(53, 29, 27));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/clock.png"))); // NOI18N
        jLabel4.setText(" Cuenta"); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        PCuenta.add(jLabel4);
        jLabel4.setBounds(10, 0, 230, 90);

        _Display.add(PCuenta);
        PCuenta.setBounds(190, 210, 240, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_Display, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_Display, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        POrden.setBackground(PastelCyan);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        POrden.setBackground(Base);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.out.println("Click orden");
        try {
            if(getEstadoMesa())
                HoraMesa(getHora());
            else;
        } catch (IOException ex) {
            Logger.getLogger(DisplayOrden.class.getName()).log(Level.SEVERE, null, ex);
        }
        setDisplay(new DisplayMenuOrden(MesaActual));
        setEstadoMesa(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        PCuenta.setBackground(PasterOrg);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        PCuenta.setBackground(Base);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        setEstadoMesa(true);
    }//GEN-LAST:event_jLabel4MouseClicked
/******************************************************************************/
    
    /**
     * @param a Panel destino a actualizar
     * Actualiza el fondo del display principal
     */
    public void setDisplay(JPanel a){
        a.setBounds(0,0,450,460);
        _Display.removeAll();
        _Display.add(a);
        _Display.updateUI();
    }
    /**
     * 
     * @param a Asigna si la mesa esta libre o no
     * Cambia el estado actual de la mesa
     */
    public void setEstadoMesa(boolean a){
        String Path;
        Path = "m" + MesaActual + "libre.bin";
        try {
            FileOutputStream fos = new FileOutputStream(Path);
            DataOutputStream dos = new DataOutputStream(fos);
            
            dos.writeBoolean(a);
            
            dos.close();
            fos.close();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DisplayOrden.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DisplayOrden.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * 
     * @return El estado actual de la mesa
     * Sirve para checar el estado actual de la mesa
     */
    public boolean getEstadoMesa() throws FileNotFoundException, IOException{
        String Path;
        Path = "m" + MesaActual + "libre.bin";
        boolean res;
        
            FileInputStream fos = new FileInputStream(Path);
            DataInputStream dos = new DataInputStream(fos);
            
            res = dos.readBoolean();
            System.out.println(res);
            
            dos.close();
            fos.close();
            
    return res;}
    /**
     * 
     * @param a Recibe la hora de ocupacion en formato string
     * Cambia la hora de ocupacion de la mesa
     */
    public void HoraMesa(String a) throws FileNotFoundException, IOException{
        String Path;
        Path = "m" + MesaActual + "hora.bin";
        
            FileOutputStream fos = new FileOutputStream(Path);
            DataOutputStream dos = new DataOutputStream(fos);
            
            dos.writeUTF(a);
            
            dos.close();
            fos.close();
    }
    /**
     * 
     * @return La hora tomada en ese momento en formato String
     */
    public String getHora() throws IOException{
        String res;
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss", Locale.US);
        LocalTime time = LocalTime.now();
        res = formatter.format(time);
        System.out.println(res);
        return res;
        
    }
    /**
     * 
     * Cambia la hora en la que se ocupa la mesa mostrada en el menu de Orden
     */
    public void setHoraDeUso() throws FileNotFoundException, IOException{
        
        String Path;
        Path = "m" + MesaActual + "libre.bin";
        FileInputStream fis = new FileInputStream(Path);
        DataInputStream dis = new DataInputStream(fis);
        
        if(!dis.readBoolean()){
            System.out.println("set hora de uso:");
            FileInputStream fis2 = new FileInputStream("m" + MesaActual + "hora.bin");
            DataInputStream dis2 = new DataInputStream(fis2);

                String time = dis2.readUTF();
                System.out.println(time);
                HoraDeUso.setText("Hora de uso: " + time);

            fis2.close();
            dis2.close();
        }
        else;
        
        fis.close();
        dis.close();
        
    }
    
    Color PastelCyan = new Color(123, 220, 255);
    Color PasterOrg = new Color(248, 178, 98);
    Color PastelPink = new Color(237, 52, 86);
    Color Base = new Color(238,230,220);
    int MesaActual;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HoraDeUso;
    private javax.swing.JPanel PCuenta;
    private javax.swing.JPanel POrden;
    private javax.swing.JPanel _Display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
