/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jessl
 */
public class DisplayMenuOrden extends javax.swing.JPanel {

    /**
     * Creates new form DisplayMenuOrden
     */
    public DisplayMenuOrden(int a) {
        MesaActual = a;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _Display = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LAme = new javax.swing.JComboBox<>();
        TAme = new javax.swing.JComboBox<>();
        SAme = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JAme = new javax.swing.JComboBox<>();
        CAme = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LFra = new javax.swing.JComboBox<>();
        TFra = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        SFra = new javax.swing.JSpinner();
        jComboBox1 = new javax.swing.JComboBox<>();
        CFra = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        JCap = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LCap = new javax.swing.JComboBox<>();
        TCap = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        SCap = new javax.swing.JSpinner();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CCap = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LCar = new javax.swing.JComboBox<>();
        TCar = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        SCar = new javax.swing.JSpinner();
        JCar = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CCar = new javax.swing.JSpinner();

        _Display.setBackground(new java.awt.Color(186, 225, 255));
        _Display.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Mesero.png"))); // NOI18N
        _Display.add(jLabel1);
        jLabel1.setBounds(250, 160, 180, 270);

        jPanel1.setBackground(new java.awt.Color(255, 255, 186));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(221, 189, 213));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Americano.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 30, 120, 120);

        LAme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tamaño", "Pichu", "Pikachu", "Raichu" }));
        LAme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAmeActionPerformed(evt);
            }
        });
        jPanel1.add(LAme);
        LAme.setBounds(130, 10, 90, 26);

        TAme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leche", "Entera", "Deslac.", "Almend." }));
        TAme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAmeActionPerformed(evt);
            }
        });
        jPanel1.add(TAme);
        TAme.setBounds(130, 40, 90, 26);

        SAme.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel1.add(SAme);
        SAme.setBounds(130, 120, 40, 30);

        jLabel8.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(53, 29, 27));
        jLabel8.setText(" Americano");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 0, 80, 30);

        jLabel10.setForeground(new java.awt.Color(53, 29, 27));
        jLabel10.setText("#Shots");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(130, 100, 40, 20);

        JAme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jarabe", "Caramelo", "Vainilla", "C.Blanco", "C.Obscuro", "Menta" }));
        JAme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAmeActionPerformed(evt);
            }
        });
        jPanel1.add(JAme);
        JAme.setBounds(130, 70, 90, 26);

        CAme.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        CAme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CAmeMouseExited(evt);
            }
        });
        jPanel1.add(CAme);
        CAme.setBounds(180, 120, 40, 30);

        jLabel14.setForeground(new java.awt.Color(53, 29, 27));
        jLabel14.setText("#Cafés");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(180, 100, 40, 20);

        _Display.add(jPanel1);
        jPanel1.setBounds(0, 0, 220, 150);

        jPanel2.setBackground(new java.awt.Color(186, 255, 201));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Frape.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 30, 120, 120);

        LFra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tamaño", "Pichu", "Pikachu", "Raichu" }));
        jPanel2.add(LFra);
        LFra.setBounds(140, 10, 90, 26);

        TFra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leche", "Entera", "Deslac.", "Almend." }));
        jPanel2.add(TFra);
        TFra.setBounds(140, 40, 90, 26);

        jLabel7.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(53, 29, 27));
        jLabel7.setText("Frape");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 0, 50, 30);

        SFra.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel2.add(SFra);
        SFra.setBounds(140, 120, 40, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jarabe", "Caramelo", "Vainilla", "C.Blanco", "C.Obscuro", "Menta" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(140, 70, 90, 26);

        CFra.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel2.add(CFra);
        CFra.setBounds(190, 120, 40, 30);

        jLabel18.setForeground(new java.awt.Color(53, 29, 27));
        jLabel18.setText("#Cafés");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(190, 100, 40, 20);

        jLabel17.setForeground(new java.awt.Color(53, 29, 27));
        jLabel17.setText("#Shots");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(140, 100, 40, 20);

        _Display.add(jPanel2);
        jPanel2.setBounds(220, 0, 230, 150);

        JCap.setBackground(new java.awt.Color(255, 223, 186));
        JCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JCapMouseExited(evt);
            }
        });
        JCap.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Capuccino.jpg"))); // NOI18N
        JCap.add(jLabel4);
        jLabel4.setBounds(0, 30, 120, 120);

        LCap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tamaño", "Pichu", "Pikachu", "Raichu" }));
        LCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LCapActionPerformed(evt);
            }
        });
        JCap.add(LCap);
        LCap.setBounds(130, 10, 90, 26);

        TCap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leche", "Entera", "Deslac.", "Almend." }));
        JCap.add(TCap);
        TCap.setBounds(130, 40, 90, 26);

        jLabel6.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(53, 29, 27));
        jLabel6.setText(" Capuccino");
        JCap.add(jLabel6);
        jLabel6.setBounds(20, 0, 80, 30);

        SCap.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        JCap.add(SCap);
        SCap.setBounds(130, 120, 40, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jarabe", "Caramelo", "Vainilla", "C.Blanco", "C.Obscuro", "Menta" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        JCap.add(jComboBox3);
        jComboBox3.setBounds(130, 70, 90, 26);

        jLabel20.setForeground(new java.awt.Color(53, 29, 27));
        jLabel20.setText("#Cafés");
        JCap.add(jLabel20);
        jLabel20.setBounds(180, 100, 40, 20);

        jLabel19.setForeground(new java.awt.Color(53, 29, 27));
        jLabel19.setText("#Shots");
        JCap.add(jLabel19);
        jLabel19.setBounds(130, 100, 40, 20);

        CCap.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        JCap.add(CCap);
        CCap.setBounds(180, 120, 40, 30);

        _Display.add(JCap);
        JCap.setBounds(0, 150, 220, 150);

        jPanel4.setBackground(new java.awt.Color(255, 179, 186));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Carajillo.jpg"))); // NOI18N
        jPanel4.add(jLabel5);
        jLabel5.setBounds(0, 30, 120, 120);

        LCar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tamaño", "Pichu", "Pikachu", "Raichu" }));
        jPanel4.add(LCar);
        LCar.setBounds(130, 10, 90, 26);

        TCar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leche", "Entera", "Deslac.", "Almend." }));
        jPanel4.add(TCar);
        TCar.setBounds(130, 40, 90, 26);

        jLabel9.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(53, 29, 27));
        jLabel9.setText("Carajillo");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(30, 0, 60, 30);

        SCar.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel4.add(SCar);
        SCar.setBounds(130, 120, 40, 30);

        JCar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jarabe", "Caramelo", "Vainilla", "C.Blanco", "C.Obscuro", "Menta" }));
        JCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCarActionPerformed(evt);
            }
        });
        jPanel4.add(JCar);
        JCar.setBounds(130, 70, 90, 26);

        jLabel15.setForeground(new java.awt.Color(53, 29, 27));
        jLabel15.setText("#Shots");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(130, 100, 40, 20);

        jLabel16.setForeground(new java.awt.Color(53, 29, 27));
        jLabel16.setText("#Cafés");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(180, 100, 40, 20);

        CCar.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel4.add(CCar);
        CCar.setBounds(180, 120, 40, 30);

        _Display.add(jPanel4);
        jPanel4.setBounds(0, 300, 220, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_Display, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_Display, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TAmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TAmeActionPerformed

    private void LCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LCapActionPerformed

    private void LAmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LAmeActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void JAmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JAmeActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void JCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCarActionPerformed

    private void CAmeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAmeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CAmeMouseExited

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        try {
            // TODO add your handling code here:
            GuardarCuenta();
        } catch (IOException ex) {
            Logger.getLogger(DisplayMenuOrden.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        try {
            // TODO add your handling code here:
            GuardarCuenta();
        } catch (IOException ex) {
            Logger.getLogger(DisplayMenuOrden.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanel2MouseExited

    private void JCapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCapMouseExited
        try {
            // TODO add your handling code here:
            GuardarCuenta();
        } catch (IOException ex) {
            Logger.getLogger(DisplayMenuOrden.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JCapMouseExited

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        try {
            // TODO add your handling code here:
            GuardarCuenta();
        } catch (IOException ex) {
            Logger.getLogger(DisplayMenuOrden.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanel4MouseExited
    
    public void GuardarCuenta() throws IOException{
        
    int CAmeValue = Integer.parseInt(CAme.getValue().toString());
    int CCapValue = Integer.parseInt(CCap.getValue().toString());
    int CCarValue = Integer.parseInt(CCar.getValue().toString());
    int CFraValue = Integer.parseInt(CFra.getValue().toString());
    int SAmeValue = Integer.parseInt(SAme.getValue().toString());
    int SCapValue = Integer.parseInt(SCap.getValue().toString());
    int SCarValue = Integer.parseInt(SCar.getValue().toString());
    int SFraValue = Integer.parseInt(CFra.getValue().toString()); 
    String i = "";
    boolean Repetido = false;
            
    String Path = "m" + MesaActual + "Cuenta.txt";
    String PathAux = "m" + MesaActual + "CuentaTemporal.txt";
        
    if((CAmeValue > 0 || CCapValue > 0 || CCarValue > 0 || CFraValue > 0)
        && (LAme.getSelectedIndex() != 0 || LCap.getSelectedIndex() != 0 
        || LCar.getSelectedIndex() != 0 || LFra.getSelectedIndex() != 0)){
        
        
        
        FileReader fr = new FileReader(Path);
        BufferedReader br = new BufferedReader(fr);
        FileWriter fwa = new FileWriter(PathAux);
        BufferedWriter bwa = new BufferedWriter(fwa);
        
        while((i = br.readLine()) != null){
            bwa.write(i + "\n");
        }
        if(CAmeValue > 0 && LAme.getSelectedIndex() != 0){
            
            String str = "Americano ";
                //Tamaño
            str = str + LAme.getSelectedItem().toString();
            
            if(TAme.getSelectedIndex() != 0){
                //leche
                str = str + " " + TAme.getSelectedItem().toString();
            }
            else{
                str = str + " " + "SLeche";
            }
            if(JAme.getSelectedIndex() != 0){
                //jarabe
                str = str + " " + JAme.getSelectedItem().toString();
            }
            else{
                str = str + " " + "SSabor";
            }
            if(SAmeValue != 0){
                //shots
                str = str + " " + SAmeValue;
            }
            else{
                str = str + " " + "Descafeinado";
            }
                //#cafes
            str = str + " " + CAmeValue;
            
            bwa.write(str);
            
            br.close();
            bwa.close();
        
        FileReader fra = new FileReader(PathAux);
        BufferedReader bra = new BufferedReader(fra);
        FileWriter fw = new FileWriter(Path);
        BufferedWriter bw = new BufferedWriter(fw);
        
        while ((i = bra.readLine()) != null) {                
            System.out.println(i);
            bw.write(i);
        }
            
        bw.close();
        bwa.close();   
            
        }
        else if(CCapValue > 0 && LCap.getSelectedIndex() != 0){
            
        }
        else if(CCarValue > 0 && LCar.getSelectedIndex() != 0){
            
        }
        else if(CFraValue > 0 && LFra.getSelectedIndex() != 0){
            
        }
        
    }
        
    }
    
    int MesaActual;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner CAme;
    private javax.swing.JSpinner CCap;
    private javax.swing.JSpinner CCar;
    private javax.swing.JSpinner CFra;
    private javax.swing.JComboBox<String> JAme;
    private javax.swing.JPanel JCap;
    private javax.swing.JComboBox<String> JCar;
    private javax.swing.JComboBox<String> LAme;
    private javax.swing.JComboBox<String> LCap;
    private javax.swing.JComboBox<String> LCar;
    private javax.swing.JComboBox<String> LFra;
    private javax.swing.JSpinner SAme;
    private javax.swing.JSpinner SCap;
    private javax.swing.JSpinner SCar;
    private javax.swing.JSpinner SFra;
    private javax.swing.JComboBox<String> TAme;
    private javax.swing.JComboBox<String> TCap;
    private javax.swing.JComboBox<String> TCar;
    private javax.swing.JComboBox<String> TFra;
    private javax.swing.JPanel _Display;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
