/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.net.URLConnection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jessl
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        setLocation(600,300);
        setUndecorated(true);
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("insignia-1.png")).getImage());
        setTitle("Poke - Cafeteria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        MostrarMesas = new javax.swing.JPanel();
        TMesas = new javax.swing.JLabel();
        MostrarVentas = new javax.swing.JPanel();
        TVentas = new javax.swing.JLabel();
        MostrarMenu = new javax.swing.JPanel();
        TMenu = new javax.swing.JLabel();
        ImprimirRecibo = new javax.swing.JPanel();
        TRecibo = new javax.swing.JLabel();
        MostrarMenu1 = new javax.swing.JPanel();
        TMenu1 = new javax.swing.JLabel();
        _Display = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(53, 29, 27));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(53, 29, 27));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });
        jPanel3.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ic_clear_24px.png"))); // NOI18N
        jLabel3.setAlignmentY(0.0F);
        jPanel3.add(jLabel3);
        jLabel3.setBounds(6, 0, 20, 20);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 20));

        jLabel1.setBackground(java.awt.Color.black);
        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText(" Poke - Cafeteria: Av. Instituto Politecnico Nacional, UPIITA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        Menu.setBackground(new java.awt.Color(53, 29, 27));
        Menu.setAlignmentX(0.0F);
        Menu.setAlignmentY(0.0F);
        Menu.setMinimumSize(new java.awt.Dimension(150, 450));
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });

        MostrarMesas.setBackground(new java.awt.Color(53, 29, 27));
        MostrarMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarMesasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MostrarMesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MostrarMesasMouseExited(evt);
            }
        });
        MostrarMesas.setLayout(null);

        TMesas.setBackground(new java.awt.Color(255, 255, 255));
        TMesas.setFont(new java.awt.Font("Blackadder ITC", 1, 24)); // NOI18N
        TMesas.setForeground(new java.awt.Color(255, 255, 255));
        TMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eevee.png"))); // NOI18N
        TMesas.setText("   Mesas");
        TMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TMesasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TMesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TMesasMouseExited(evt);
            }
        });
        MostrarMesas.add(TMesas);
        TMesas.setBounds(10, 0, 130, 60);

        MostrarVentas.setBackground(new java.awt.Color(53, 29, 27));
        MostrarVentas.setLayout(null);

        TVentas.setBackground(new java.awt.Color(255, 255, 255));
        TVentas.setFont(new java.awt.Font("Blackadder ITC", 1, 24)); // NOI18N
        TVentas.setForeground(new java.awt.Color(255, 255, 255));
        TVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pokecoin.png"))); // NOI18N
        TVentas.setText("  Ventas");
        TVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TVentasMouseExited(evt);
            }
        });
        MostrarVentas.add(TVentas);
        TVentas.setBounds(10, 0, 130, 60);

        MostrarMenu.setBackground(new java.awt.Color(53, 29, 27));
        MostrarMenu.setLayout(null);

        TMenu.setBackground(new java.awt.Color(255, 255, 255));
        TMenu.setFont(new java.awt.Font("Blackadder ITC", 1, 24)); // NOI18N
        TMenu.setForeground(new java.awt.Color(255, 255, 255));
        TMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/backpack.png"))); // NOI18N
        TMenu.setText("   Menú");
        TMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TMenuMouseExited(evt);
            }
        });
        MostrarMenu.add(TMenu);
        TMenu.setBounds(10, 0, 130, 60);

        ImprimirRecibo.setBackground(new java.awt.Color(53, 29, 27));
        ImprimirRecibo.setLayout(null);

        TRecibo.setBackground(new java.awt.Color(255, 255, 255));
        TRecibo.setFont(new java.awt.Font("Blackadder ITC", 1, 24)); // NOI18N
        TRecibo.setForeground(new java.awt.Color(255, 255, 255));
        TRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/smartphone.png"))); // NOI18N
        TRecibo.setText("   Recibo");
        TRecibo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TReciboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TReciboMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TReciboMouseExited(evt);
            }
        });
        ImprimirRecibo.add(TRecibo);
        TRecibo.setBounds(20, 0, 120, 60);

        MostrarMenu1.setBackground(new java.awt.Color(53, 29, 27));
        MostrarMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MostrarMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MostrarMenu1MouseExited(evt);
            }
        });
        MostrarMenu1.setLayout(null);

        TMenu1.setBackground(new java.awt.Color(255, 255, 255));
        TMenu1.setFont(new java.awt.Font("Blackadder ITC", 1, 22)); // NOI18N
        TMenu1.setForeground(new java.awt.Color(255, 255, 255));
        TMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/map.png"))); // NOI18N
        TMenu1.setText("Conócenos");
        TMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TMenu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TMenu1MouseExited(evt);
            }
        });
        MostrarMenu1.add(TMenu1);
        TMenu1.setBounds(10, 0, 130, 60);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MostrarMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MostrarVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MostrarMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImprimirRecibo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MostrarMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MostrarMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MostrarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MostrarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ImprimirRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(MostrarMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 150, 450));

        _Display.setBackground(new java.awt.Color(238, 230, 220));
        _Display.setPreferredSize(new java.awt.Dimension(450, 450));
        _Display.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Componente 1 – 1.png"))); // NOI18N
        _Display.add(jLabel2);
        jLabel2.setBounds(60, 40, 340, 150);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sylveon.gif"))); // NOI18N
        _Display.add(jLabel4);
        jLabel4.setBounds(0, 328, 110, 120);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Componente 2 – 1.png"))); // NOI18N
        _Display.add(jLabel6);
        jLabel6.setBounds(90, 210, 350, 100);

        jPanel1.add(_Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 450, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        jPanel3.setBackground(Color.red);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(DeepBrown);
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        Color CrossBg = new Color(200,0,0);
        jPanel3.setBackground(CrossBg);
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Sound();
            //System.exit(0);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jPanel3.setBackground(Color.red);
        int res = JOptionPane.showConfirmDialog(null, "Desea cerrar del programa?", "Poke - Cafeteria UPIITA", JOptionPane.YES_NO_OPTION);
        if(res == 0){
            LiberarMesas();
            LiberarCuentasTemporales();
            System.exit(0);
        }
        else;
    }//GEN-LAST:event_jPanel3MouseReleased

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void MostrarMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarMesasMouseClicked
        // TODO add your handling code here:
        Mesas ME = new Mesas();
        ME.setBounds(0,-45,450,540);
        _Display.removeAll();
        _Display.add(ME);
        _Display.updateUI();
    }//GEN-LAST:event_MostrarMesasMouseClicked

    private void MostrarMesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarMesasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarMesasMouseEntered

    private void TMesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMesasMouseExited
        // TODO add your handling code here:
        MostrarMesas.setBackground(Base);
        TMesas.setForeground(Color.white);
        
    }//GEN-LAST:event_TMesasMouseExited

    private void MostrarMesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarMesasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarMesasMouseExited

    private void TMesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMesasMouseEntered
        // TODO add your handling code here:
        MostrarMesas.setBackground(PastelRed);
        TMesas.setForeground(Base);
    }//GEN-LAST:event_TMesasMouseEntered

    private void TMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMesasMouseClicked
        // TODO add your handling code here:
        Mesas ME = new Mesas();
        ME.setBounds(0,-45,450,540);
        try {
            ME.ChangeIcon1();
            ME.ChangeIcon2();
            ME.ChangeIcon3();
            ME.ChangeIcon4();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        _Display.removeAll();
        _Display.add(ME);
        _Display.updateUI();
    }//GEN-LAST:event_TMesasMouseClicked

    private void TVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TVentasMouseClicked
        // TODO add your handling code here:
        DisplayLogin log = new DisplayLogin();
        log.setBounds(0,-45,450,540);
        _Display.removeAll();
        _Display.add(log);
        _Display.updateUI();
    }//GEN-LAST:event_TVentasMouseClicked

    private void TVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TVentasMouseEntered
        // TODO add your handling code here:
        MostrarVentas.setBackground(PastelOrg);
        TVentas.setForeground(Base);
    }//GEN-LAST:event_TVentasMouseEntered

    private void TVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TVentasMouseExited
        // TODO add your handling code here:
        MostrarVentas.setBackground(Base);
        TVentas.setForeground(Color.white);
    }//GEN-LAST:event_TVentasMouseExited

    private void TMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMenuMouseClicked
        // TODO add your handling code here:
        DisplayMenu men = new DisplayMenu();
        men.setBounds(0,0,450,540);
        _Display.removeAll();
        _Display.add(men);
        _Display.updateUI();
    }//GEN-LAST:event_TMenuMouseClicked

    private void TMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMenuMouseEntered
        // TODO add your handling code here:
        MostrarMenu.setBackground(PastelYel);
        TMenu.setForeground(Base);
    }//GEN-LAST:event_TMenuMouseEntered

    private void TMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMenuMouseExited
        // TODO add your handling code here:
        MostrarMenu.setBackground(Base);
        TMenu.setForeground(Color.white);
    }//GEN-LAST:event_TMenuMouseExited

    private void TReciboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TReciboMouseClicked
        // TODO add your handling code here:
        DisplayLogin log = new DisplayLogin();
        log.setBounds(0,-45,450,540);
        _Display.removeAll();
        _Display.add(log);
        _Display.updateUI();
    }//GEN-LAST:event_TReciboMouseClicked

    private void TReciboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TReciboMouseEntered
        // TODO add your handling code here:
        ImprimirRecibo.setBackground(PastelGrn);
        TRecibo.setForeground(Base);
    }//GEN-LAST:event_TReciboMouseEntered

    private void TReciboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TReciboMouseExited
        // TODO add your handling code here:
        ImprimirRecibo.setBackground(Base);
        TRecibo.setForeground(Color.white);
    }//GEN-LAST:event_TReciboMouseExited

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuMouseClicked

    private void TMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMenu1MouseClicked
        try {
            // TODO add your handling code here:
            UErreEle();
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TMenu1MouseClicked

    private void TMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMenu1MouseEntered
        // TODO add your handling code here:
        MostrarMenu1.setBackground(PastelBlu);
        TMenu1.setForeground(Base);
    }//GEN-LAST:event_TMenu1MouseEntered

    private void TMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMenu1MouseExited
        // TODO add your handling code here:
        MostrarMenu1.setBackground(Base);
        TMenu1.setForeground(Color.WHITE);
    }//GEN-LAST:event_TMenu1MouseExited

    private void MostrarMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarMenu1MouseEntered
        // TODO add your handling code here:
        MostrarMenu1.setBackground(PastelBlu);
    }//GEN-LAST:event_MostrarMenu1MouseEntered

    private void MostrarMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarMenu1MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MostrarMenu1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    static int xx, yy;
    Color PastelRed = new Color(255, 179, 186);
    Color PastelOrg = new Color(255, 223, 186);
    Color PastelYel = new Color(255, 255, 186);
    Color PastelGrn = new Color(186, 255, 201);
    Color PastelBlu = new Color(186, 225, 255);
    
    Color Base = new Color(53,29,27);
    Color DeepBrown = new Color(53,29,27);
    Color DarkBrown = new Color(80, 40, 0);
    
    public void setDisplay(JPanel a){
        a.setBounds(0,-45,450,540);
        _Display.removeAll();
        _Display.add(a);
        _Display.updateUI();
    }
    
    public void LiberarMesas(){
        String Path;
        
        for(int i = 1; i < 5; i++){
        Path = "m" + i + "libre.bin";
        try {
            FileOutputStream fos = new FileOutputStream(Path);
            DataOutputStream dos = new DataOutputStream(fos);
            
            dos.writeBoolean(true);
            
            dos.close();
            fos.close();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DisplayOrden.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DisplayOrden.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }
    
    public void LiberarCuentasTemporales(){
        String Path;
        
        for(int i = 1; i < 5; i++){
        Path = "m" + i + "CuentaTemporal.txt";
        
            try {
                FileWriter fw = new FileWriter(Path);
                BufferedWriter bw = new BufferedWriter(fw);
                
                bw.write("");
                
            } catch (Exception e) {
            }
        
        }
    }
    
    public void UErreEle() throws MalformedURLException, IOException, URISyntaxException{
        String url_open ="https://www.tiktok.com/@jamiejoart/video/6826009123377728774?lang=es";
        URI a = new URI(url_open);
        java.awt.Desktop.getDesktop().browse(a);
    }
    
    public void Sound() throws FileNotFoundException{
        
        String SFX = "";
        SFX = "N.wav";
        try {
    File yourFile = new File(SFX);
    AudioInputStream stream;
    AudioFormat format;
    DataLine.Info info;
    Clip clip;

    stream = AudioSystem.getAudioInputStream(yourFile);
    format = stream.getFormat();
    info = new DataLine.Info(Clip.class, format);
    clip = (Clip) AudioSystem.getLine(info);
    clip.open(stream);
    clip.start();
    }
        catch ( IOException | LineUnavailableException | UnsupportedAudioFileException e) {
            //whatevers
    }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ImprimirRecibo;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MostrarMenu;
    private javax.swing.JPanel MostrarMenu1;
    private javax.swing.JPanel MostrarMesas;
    private javax.swing.JPanel MostrarVentas;
    private javax.swing.JLabel TMenu;
    private javax.swing.JLabel TMenu1;
    private javax.swing.JLabel TMesas;
    private javax.swing.JLabel TRecibo;
    private javax.swing.JLabel TVentas;
    private javax.swing.JPanel _Display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
